// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file catimages.proto (package catimages, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CatImageRequest, CatImageResponse } from "./catimages_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service catimages.CatImageService
 */
export const CatImageService = {
  typeName: "catimages.CatImageService",
  methods: {
    /**
     * @generated from rpc catimages.CatImageService.GetCatImage
     */
    getCatImage: {
      name: "GetCatImage",
      I: CatImageRequest,
      O: CatImageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

