// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file greeting.proto (package greeting, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GreetingMessage, Person } from "./greeting_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greeting.Greeter
 */
export const Greeter = {
  typeName: "greeting.Greeter",
  methods: {
    /**
     * @generated from rpc greeting.Greeter.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: Person,
      O: GreetingMessage,
      kind: MethodKind.Unary,
    },
  }
} as const;

